### ISSUE TITLE
Can this package use the data downloaded from CMIP6?

### ISSUE THREAD

**Issue by mystery-ss** [lemuscanovas/synoptReg#1]
AS the title, I want to use the nc files form CMIP6 . I have tried some methods to change the nc files into RDS files , but the function tidy_nc  always reports error ：
```
Problem with `mutate()` input `mo`.
x do not know how to convert 'x' to class “POSIXlt”
i Input `mo` is `month(time)`.
```

**Comment by lemuscanovas** [comment]
Dear mystery-ss,
First of all, sorry for the delay in the response.

`tidy_nc` is not intended to read nc files. To use the functions provided in `synoptReg`, you previously need to use the `ReadNetCDF` function fromt the `metR` package.

Here I provide you an example:

```
slp_file <- system.file("extdata", "mslp_ei.nc", package = "synoptReg") # nc stored inside synoptReg
slp <- ReadNetCDF(file = slp_file,vars = "msl",out = "data.frame") %>% # reading nc data
  setNames(c("lat","lon","value","time")) %>% # !! To use the synoptReg package, you need this names
  select(lon,lat,time, value) %>% mutate(time = as.Date(time)) # and then you need to reorder in this way (lon,lat,time,value)
```
I hope it will be helpful to you

**Comment by mystery-ss** [comment]
Thanks for your reply.
And I want to know how to solve the following problems when I use function pca_decision and synoptclas:

example:
vars10 <- tidy_nc(x = list(slp90,hgt90), name_vars = c("slp","hgt"))
info10 <- pca_decision(vars10,ncomp = 30,norm = T,matrix_mode = "S-mode")
cl10 <- synoptclas(vars10,ncomp = 4,norm = T,matrix_mode = "S-mode")

Error in princomp.default(., scores = T) : 
  'princomp' can only be used with more units than variables

"slp90" and "hgt90" are the data which I downloaded from function download_ncep.

**Comment by lemuscanovas** [comment]
The error you printed is related to a limitation of `princomp` function. 
`'princomp' can only be used with more units than variables` means that you need more rows than variables. For example, in your case, you probably are trying to classify few days, so in the `S-mode` PCA the grid points are the variables and the days are the observations. If you have more grid points than days (more variables than observations), `princomp` displays this error.

In this case, and for solve your problem, you only need to change the type of matrix structure into a `T-mode`: days are the variables, and grid points are the rows.

Usually, the `S-mode` is used to classify long time series; and `T-mode` for classify few days (i.e. Torrential events).

**Comment by mystery-ss** [comment]
Thanks for your explanation, 'T-mode' is available.


I am still&nbsp;little confused about it:
My&nbsp;data is for 10years (2010-2019), I think this should be regarded as long time series,right?


When I just use one variable('slp90' or 'hgt90'),'S-mode' can be used but 'T-mode' can't. 


After reading your articles, in my opinion，the&nbsp;meaning of&nbsp;these&nbsp;two&nbsp;modes are different classification methods, so the same data will get different results in different modes, or just my understanding is wrong？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Marc Lemus-Canovas"<notifications@github.com&gt;; 
发送时间: 2020年10月23日(星期五) 下午3:11
收件人: "lemuscanovas/synoptReg"<synoptReg@noreply.github.com&gt;; 
抄送: "mystery"<844465709@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lemuscanovas/synoptReg] Can this package use the data downloaded from CMIP6? (#1)





 
The error you printed is related to a limitation of princomp function.
 'princomp' can only be used with more units than variables means that you need more rows than variables. For example, in your case, you probably are trying to classify few days, so in the S-mode PCA the grid points are the variables and the days are the observations. If you have more grid points than days (more variables than observations), princomp displays this error.
 
In this case, and for solve your problem, you only need to change the type of matrix structure into a T-mode: days are the variables, and grid points are the rows.
 
Usually, the S-mode is used to classify long time series; and T-mode for classify few days (i.e. Torrential events).

**Comment by lemuscanovas** [comment]
Logically, using the T-mode or S-mode implies different results, because the matrix structure and method change. When you apply a PCA in a s-mode matrix you cannot obtain a final classification, so you need to apply a cluster algorithm. The T-mode is a more direct approach.

With regards to the length of the time series, and to obtain robust results, the observations need to be larger than variables.
_Hair et al. [2000]_ recommend a number of observations five times higher than the number of variables. In addition, in Esteban et al. (2006), you can find: _**As the number of variables (days) would largely exceed the number of observations (grid points)** and also owing to the high computation requirements of T-mode(Huth, 2000), an S-mode data matrix is used (Richman,1986),  the  variables  being  the  grid  points  and  the  days  being  the  observations._ 

So you can see as it is important to have a large number of observations. If you are working in a small domain or only using one atmospheric variable, you don't need many observations because in the S-mode you have few variables (grid points). However, if you use many atmospheric variables and you have 2 years of days for classifying, you only can use the T-mode, because depending on the resolution of the atmospheric your number of grid points could be larger than the number of days. In this case, T-mode place days into variables, and grid points into rows.

I highly recommend you to take a look at references cited in the package website: https://lemuscanovas.github.io/synoptreg/index.html

**Comment by mystery-ss** [comment]
Thank you very much for your suggestion.These days, I have read several articles you mentioned.


Therefore, when I want to explore the influence of different atmospheric patterns on ozone by classifying summer data every ten years, should I use T-mode?






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Marc Lemus-Canovas"<notifications@github.com&gt;; 
发送时间: 2020年10月24日(星期六) 下午5:23
收件人: "lemuscanovas/synoptReg"<synoptReg@noreply.github.com&gt;; 
抄送: "mystery"<844465709@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lemuscanovas/synoptReg] Can this package use the data downloaded from CMIP6? (#1)





 
Logically, using the T-mode or S-mode implies different results, because the matrix structure and method change. When you apply a PCA in a s-mode matrix you cannot obtain a final classification, so you need to apply a cluster algorithm. The T-mode is a more direct approach.
 
With regards to the length of the time series, and to obtain robust results, the observations need to be larger than variables.
 Hair et al. [2000] recommend a number of observations five times higher than the number of variables. In addition, in Esteban et al. (2006), you can find: As the number of variables (days) would largely exceed the number of observations (grid points) and also owing to the high computation requirements of T-mode(Huth, 2000), an S-mode data matrix is used (Richman,1986),  the  variables  being  the  grid  points  and  the  days  being  the  observations.
 
So you can see as it is important to have a large number of observations. If you are working in a small domain or only using one atmospheric variable, you don't need many observations because in the S-mode you have few variables (grid points). However, if you use many atmospheric variables and you have 2 years of days for classifying, you only can use the T-mode, because depending on the resolution of the atmospheric your number of grid points could be larger than the number of days. In this case, T-mode place days into variables, and grid points into rows.
 
I highly recommend you to take a look at references cited in the package website: https://lemuscanovas.github.io/synoptreg/index.html

**Comment by lemuscanovas** [comment]
It depends on the spatial resolution and number of variables you're trying to classify. Check which matrix (S or T) disposition helps you to do the matrix longer (more rows than columns).
