### ISSUE TITLE
Problema al leer los archivos .nc de la instalación

### ISSUE THREAD

**Issue by paco-ceam** [lemuscanovas/synoptReg#2]
Bon dia

Quiero comenzar a utilizar synoptReg pero he encontrado un problema al replicar la sección Environment to circulation. Cuando va a leer los archivos .nc me da error:
```

> # Reading the data stored in the NetCDFs files as tibbles. it can take a while.
> slp <- ReadNetCDF(file = slp_file,vars = "msl",out = "data.frame") %>%
+   setNames(c("lat","lon","value","time")) %>%
+   select(lon,lat,time, value) %>% mutate(time = as.Date(time))
Error: Problem with `mutate()` input `time`.
x 'origin' must be supplied
i Input `time` is `as.Date(time)`.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/dplyr:::mutate_error>
Problem with `mutate()` input `time`.
x 'origin' must be supplied
i Input `time` is `as.Date(time)`.
Backtrace:
  1. `%>%`(...)
 10. base::.handleSimpleError(...)
 11. dplyr:::h(simpleError(msg, call))
Run `rlang::last_trace()` to see the full context.
```
He ido instalando los paquetes que me pedía por lo que no creo que sea por falta de ningún paquete. ¿Alguna idea?
Gracias

**Comment by lemuscanovas** [comment]
Hola Paco,

Efectivamente hay un error en el código del tutorial. Lo tengo pendiente de arreglar. Simplemente se trata del orden de las variables. Si solo corres la primera linea: 

`slp <- ReadNetCDF(file = slp_file,vars = "msl",out = "data.frame")` verás que el orden de las columnas es:  time, latitude, longitude,  msl.

Por lo tanto solo hay que renombrar correctamente las variables:
`
slp <- ReadNetCDF(file = slp_file,vars = "msl",out = "data.frame") %>%
 setNames(c("time","lat","lon","value")) %>%
select(lon,lat,time, value) %>% mutate(time = as.Date(time))
`

Así ya debería funcionarte. Solo necesitas la librería metR, el tidyverse y synoptReg.
Un saludo!

**Comment by paco-ceam** [comment]
Muchas gracias por la respuesta, en cuanto pueda lo pruebo. Seguimos en contacto.
