### ISSUE TITLE
"No protocal specified" problem.

### ISSUE THREAD

**Issue by NMC-DAVE** [lemuscanovas/synoptReg#6]
Hi, Lemus-Canovas:
       Great work for synoptic climatology research. I would like to use the SOM classification.
I have a problem. When I loaded the library in Rstudio server (linux), I got the following message:

```
> library(synoptReg)
No protocol specified
No protocol specified

****
Welcome to synoptReg! 
Using synoptReg for research publication?  Please cite it!
I'm an early career researcher and every citation matters.
****

Warning message:
In fun(libname, pkgname) : couldn't connect to display ":0"
```

So how can I avoid this. thanks very much.

**Comment by lemuscanovas** [comment]
Hi,
I really don't understand what the problem is, does this warning prevent you from loading the library functions?
I propose an alternative option:

- uninstall your current version (```remove.packages("synoptReg")```) and install via github:

```r
#install.packages("remotes")
remotes::install_github("lemuscanovas/synoptReg")
library(synoptReg)
```

Tell me if it works! 
Marc

**Comment by lemuscanovas** [comment]
Take a look at the following post: https://support.rstudio.com/hc/en-us/articles/360019922654-Working-with-packages-that-require-X11-and-or-cairo-on-RStudio-Server-Pro

This problem could be related to X11...
