### ISSUE TITLE
tidy_nc

### ISSUE THREAD

**Issue by fipoucat** [lemuscanovas/synoptReg#8]
I face an error:

vars <- tidy_nc(x = slp, name_vars = "mslp")
Error in tidy_nc(x = slp, name_vars = "mslp") : 
  could not find function "tidy_nc"

**Comment by lemuscanovas** [comment]
Hi!
I am doing a major update of the package and `tidy_nc` will not be longer available. 
Please, download the latest version available from github: `remotes::install_github("lemuscanovas/synoptReg")`

In short, you can proceed in the following way using the new functions `read_nc` and `as_synoptReg`:
```r 
slp <- read_nc("file.nc") %>% as_synoptReg()
```
I am also currently updating the synoptReg website, take a look at the new codes: https://lemuscanovas.github.io/synoptreg/articles/classification_metrics.html

Please, be aware that some codes and especially texts might be still old.
Feel free to contact me if you have any doubt or suggestion.

**Comment by fipoucat** [comment]
Thank you Marc, well noted for the update, that's great news.
All the best
